### ISSUE TITLE
[Bug] Effort with pie

### ISSUE THREAD

**Issue by DidierRLopes** [GamestonkTerminal/GamestonkTerminal#1371]
![Screenshot 2022-02-15 at 14 33 25](https://user-images.githubusercontent.com/25267873/154083048-4652b8ac-ca09-42ff-97f7-7a29f0c3a4ce.png)

**Comment by minhhoang1023** [comment]
@DidierRLopes what were your portfolio's tickers?

**Comment by DidierRLopes** [comment]
It happens regardless, but try TSLA and MSFT for instance

**Comment by jmaslek** [comment]
@DidierRLopes -- with AAPL and TSLA (I can't recreate with MSFT either)
![efret1](https://user-images.githubusercontent.com/18151143/154555855-721606c6-6036-4a70-8b13-77b2182d68c2.png)

**Comment by jmaslek** [comment]
@DidierRLopes can you close this if I fixed it?

**Comment by DidierRLopes** [comment]
I still get it, may be due to my version. Will do poetry install and try again

**Comment by DidierRLopes** [comment]
That did it 😄  @jmaslek
